all:
	# sudo npm -g install browserify 
	# npm install axios
	npm install jquery
	npm install underscore 
	browserify --debug Dobi.browser.js > CupLab.Dobi.browser.js
	cp CupLab.Dobi.browser.js ../js/

clean:
